os: Visual Studio 2015

platform: 
  - x86
  - x64

configuration:
  - Release

init:
  - cmd: cmake --version
 

before_build:
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="x86" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: INSTALL.vcxproj